"""Initial migration with final models

Revision ID: 07210615c51d
Revises: 
Create Date: 2025-08-12 18:50:39.727876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07210615c51d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edisi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('tahun', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('countdown_title', sa.String(length=200), nullable=True),
    sa.Column('countdown_target_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('santri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_student_id', sa.String(length=50), nullable=False),
    sa.Column('nis', sa.String(length=30), nullable=False),
    sa.Column('nama', sa.String(length=150), nullable=False),
    sa.Column('kabupaten', sa.String(length=100), nullable=True),
    sa.Column('asrama', sa.String(length=50), nullable=True),
    sa.Column('no_hp_wali', sa.String(length=20), nullable=True),
    sa.Column('jenis_kelamin', sa.String(length=10), nullable=True),
    sa.Column('kelas_formal', sa.String(length=50), nullable=True),
    sa.Column('kelas_ngaji', sa.String(length=50), nullable=True),
    sa.Column('status_santri', sa.String(length=20), nullable=True),
    sa.Column('nama_jabatan', sa.String(length=100), nullable=True),
    sa.Column('status_jabatan', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_student_id'),
    sa.UniqueConstraint('nis')
    )
    op.create_table('izin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('santri_id', sa.Integer(), nullable=False),
    sa.Column('tanggal_berakhir', sa.Date(), nullable=False),
    sa.Column('keterangan', sa.Text(), nullable=False),
    sa.Column('edisi_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['edisi_id'], ['edisi.id'], ),
    sa.ForeignKeyConstraint(['santri_id'], ['santri.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('santri_id', 'edisi_id', name='uq_izin_santri_edisi')
    )
    op.create_table('partisipan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edisi_id', sa.Integer(), nullable=False),
    sa.Column('santri_id', sa.Integer(), nullable=False),
    sa.Column('kategori', sa.String(length=100), nullable=False),
    sa.Column('tanggal_ditetapkan', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['edisi_id'], ['edisi.id'], ),
    sa.ForeignKeyConstraint(['santri_id'], ['santri.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('santri_id', 'edisi_id', name='uq_partisipan_santri_edisi')
    )
    op.create_table('rombongan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edisi_id', sa.Integer(), nullable=False),
    sa.Column('nama_rombongan', sa.String(length=100), nullable=False),
    sa.Column('penanggung_jawab_putra', sa.String(length=100), nullable=True),
    sa.Column('kontak_person_putra', sa.String(length=20), nullable=True),
    sa.Column('penanggung_jawab_putri', sa.String(length=100), nullable=True),
    sa.Column('kontak_person_putri', sa.String(length=20), nullable=True),
    sa.Column('nomor_rekening', sa.String(length=50), nullable=True),
    sa.Column('cakupan_wilayah', sa.JSON(), nullable=True),
    sa.Column('jadwal_pulang', sa.DateTime(), nullable=True),
    sa.Column('batas_pembayaran_pulang', sa.Date(), nullable=True),
    sa.Column('jadwal_berangkat', sa.DateTime(), nullable=True),
    sa.Column('batas_pembayaran_berangkat', sa.Date(), nullable=True),
    sa.Column('titik_jemput_berangkat', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['edisi_id'], ['edisi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rombongan_id', sa.Integer(), nullable=False),
    sa.Column('nama_armada', sa.String(length=100), nullable=True),
    sa.Column('nomor_lambung', sa.String(length=50), nullable=True),
    sa.Column('plat_nomor', sa.String(length=20), nullable=True),
    sa.Column('kuota', sa.Integer(), nullable=False),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('gmaps_share_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['rombongan_id'], ['rombongan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarif',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titik_turun', sa.String(length=100), nullable=False),
    sa.Column('harga_bus', sa.Integer(), nullable=False),
    sa.Column('fee_korda', sa.Integer(), nullable=True),
    sa.Column('rombongan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rombongan_id'], ['rombongan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pendaftaran',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edisi_id', sa.Integer(), nullable=False),
    sa.Column('santri_id', sa.Integer(), nullable=False),
    sa.Column('rombongan_pulang_id', sa.Integer(), nullable=True),
    sa.Column('rombongan_kembali_id', sa.Integer(), nullable=True),
    sa.Column('status_pulang', sa.String(length=20), nullable=True),
    sa.Column('metode_pembayaran_pulang', sa.String(length=20), nullable=True),
    sa.Column('bus_pulang_id', sa.Integer(), nullable=True),
    sa.Column('titik_turun', sa.String(length=100), nullable=True),
    sa.Column('status_kembali', sa.String(length=20), nullable=True),
    sa.Column('metode_pembayaran_kembali', sa.String(length=20), nullable=True),
    sa.Column('bus_kembali_id', sa.Integer(), nullable=True),
    sa.Column('titik_jemput_kembali', sa.String(length=100), nullable=True),
    sa.Column('total_biaya', sa.Integer(), nullable=False),
    sa.Column('tanggal_pendaftaran', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bus_kembali_id'], ['bus.id'], ),
    sa.ForeignKeyConstraint(['bus_pulang_id'], ['bus.id'], ),
    sa.ForeignKeyConstraint(['edisi_id'], ['edisi.id'], ),
    sa.ForeignKeyConstraint(['rombongan_kembali_id'], ['rombongan.id'], ),
    sa.ForeignKeyConstraint(['rombongan_pulang_id'], ['rombongan.id'], ),
    sa.ForeignKeyConstraint(['santri_id'], ['santri.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('santri_id', 'edisi_id', name='uq_pendaftaran_santri_edisi')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('bus_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bus_id'], ['bus.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('absen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pendaftaran_id', sa.Integer(), nullable=False),
    sa.Column('nama_absen', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('dicatat_oleh_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dicatat_oleh_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['pendaftaran_id'], ['pendaftaran.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('action_type', sa.String(length=20), nullable=True),
    sa.Column('feature', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_log_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_feature'), ['feature'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('user_rombongan',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rombongan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rombongan_id'], ['rombongan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'rombongan_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_rombongan')
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_activity_log_feature'))
        batch_op.drop_index(batch_op.f('ix_activity_log_action_type'))

    op.drop_table('activity_log')
    op.drop_table('absen')
    op.drop_table('user')
    op.drop_table('pendaftaran')
    op.drop_table('tarif')
    op.drop_table('bus')
    op.drop_table('rombongan')
    op.drop_table('partisipan')
    op.drop_table('izin')
    op.drop_table('santri')
    op.drop_table('role')
    op.drop_table('edisi')
    # ### end Alembic commands ###
