"""Tambah kolom jabatan ke model Santri

Revision ID: 0d3b7caa114e
Revises: 94da95abe6d2
Create Date: 2025-08-12 00:58:31.621485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d3b7caa114e'
down_revision = '94da95abe6d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('santri', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jabatan', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('santri', schema=None) as batch_op:
        batch_op.drop_column('jabatan')

    # ### end Alembic commands ###
