"""Tambah PJ putri ke model Rombongan

Revision ID: 1f51004e7d0c
Revises: f1be79a41b38
Create Date: 2025-08-08 00:22:38.142091

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1f51004e7d0c'
down_revision = 'f1be79a41b38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rombongan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('penanggung_jawab_putra', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('kontak_person_putra', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('penanggung_jawab_putri', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('kontak_person_putri', sa.String(length=20), nullable=True))
        batch_op.drop_column('kontak_person')
        batch_op.drop_column('penanggung_jawab')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rombongan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('penanggung_jawab', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('kontak_person', mysql.VARCHAR(length=20), nullable=False))
        batch_op.drop_column('kontak_person_putri')
        batch_op.drop_column('penanggung_jawab_putri')
        batch_op.drop_column('kontak_person_putra')
        batch_op.drop_column('penanggung_jawab_putra')

    # ### end Alembic commands ###
