"""penyesuaian api student

Revision ID: 20c453caeaa9
Revises: beb1d03093ee
Create Date: 2025-08-31 22:41:19.786829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20c453caeaa9'
down_revision = 'beb1d03093ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('santri', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['api_student_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('santri', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
