"""Tambah Traccar Device ID ke model Bus

Revision ID: 319fe9ebca20
Revises: 07210615c51d
Create Date: 2025-08-13 00:58:16.920568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '319fe9ebca20'
down_revision = '07210615c51d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('traccar_device_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['traccar_device_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bus', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('traccar_device_id')

    # ### end Alembic commands ###
