"""Split pondok fee deposit tracking

Revision ID: 3a94d5e09a9d
Revises: 55db64609013
Create Date: 2025-08-19 16:31:53.705544

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a94d5e09a9d'
down_revision = '55db64609013'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rombongan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_setoran_pondok_pulang', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_setoran_pondok_kembali', sa.Integer(), nullable=True))
        batch_op.drop_column('total_setoran_pondok')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rombongan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_setoran_pondok', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('total_setoran_pondok_kembali')
        batch_op.drop_column('total_setoran_pondok_pulang')

    # ### end Alembic commands ###
