"""Implementasi model Bus dan struktur Pulang-Berangkat

Revision ID: 3ee1c9ca82d8
Revises: ef8f43aa228b
Create Date: 2025-08-06 04:05:58.380269

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ee1c9ca82d8'
down_revision = 'ef8f43aa228b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rombongan_id', sa.Integer(), nullable=False),
    sa.Column('nama_armada', sa.String(length=100), nullable=True),
    sa.Column('nomor_lambung', sa.String(length=50), nullable=True),
    sa.Column('plat_nomor', sa.String(length=20), nullable=True),
    sa.Column('kuota', sa.Integer(), nullable=False),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['rombongan_id'], ['rombongan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pendaftaran', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bus_pulang_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bus_kembali_id', sa.Integer(), nullable=True))
        batch_op.alter_column('jenis_perjalanan',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('titik_turun',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.create_foreign_key(None, 'bus', ['bus_pulang_id'], ['id'])
        batch_op.create_foreign_key(None, 'bus', ['bus_kembali_id'], ['id'])
        batch_op.drop_column('nomor_bus')

    with op.batch_alter_table('rombongan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jadwal_kembali', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('titik_kumpul_kembali', sa.String(length=200), nullable=True))
        batch_op.drop_column('kuota')
        batch_op.drop_column('nama_armada')
        batch_op.drop_column('keterangan_armada')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rombongan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keterangan_armada', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('nama_armada', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('kuota', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('titik_kumpul_kembali')
        batch_op.drop_column('jadwal_kembali')

    with op.batch_alter_table('pendaftaran', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nomor_bus', mysql.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('titik_turun',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('jenis_perjalanan',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('bus_kembali_id')
        batch_op.drop_column('bus_pulang_id')

    op.drop_table('bus')
    # ### end Alembic commands ###
