"""Add provinsi to Santri model

Revision ID: 4c933411a49f
Revises: 3a94d5e09a9d
Create Date: 2025-08-25 04:15:45.071385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c933411a49f'
down_revision = '3a94d5e09a9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('santri', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provinsi', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('santri', schema=None) as batch_op:
        batch_op.drop_column('provinsi')

    # ### end Alembic commands ###
