"""Initial migration with all tables

Revision ID: 4f8339332785
Revises: 
Create Date: 2025-08-05 02:13:37.433496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f8339332785'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rombongan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_rombongan', sa.String(length=100), nullable=False),
    sa.Column('penanggung_jawab', sa.String(length=100), nullable=False),
    sa.Column('kontak_person', sa.String(length=20), nullable=False),
    sa.Column('nomor_rekening', sa.String(length=50), nullable=False),
    sa.Column('jadwal_keberangkatan', sa.DateTime(), nullable=False),
    sa.Column('titik_kumpul', sa.String(length=200), nullable=False),
    sa.Column('nama_armada', sa.String(length=100), nullable=True),
    sa.Column('keterangan_armada', sa.Text(), nullable=True),
    sa.Column('cakupan_wilayah', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('santri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_student_id', sa.String(length=50), nullable=False),
    sa.Column('nis', sa.String(length=30), nullable=False),
    sa.Column('nama', sa.String(length=150), nullable=False),
    sa.Column('kabupaten', sa.String(length=100), nullable=True),
    sa.Column('asrama', sa.String(length=50), nullable=True),
    sa.Column('no_hp_wali', sa.String(length=20), nullable=True),
    sa.Column('jenis_kelamin', sa.String(length=10), nullable=True),
    sa.Column('kelas_formal', sa.String(length=50), nullable=True),
    sa.Column('kelas_ngaji', sa.String(length=50), nullable=True),
    sa.Column('status_santri', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_student_id'),
    sa.UniqueConstraint('nis')
    )
    op.create_table('izin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('santri_id', sa.Integer(), nullable=False),
    sa.Column('tanggal_berakhir', sa.Date(), nullable=False),
    sa.Column('keterangan', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['santri_id'], ['santri.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('santri_id')
    )
    op.create_table('partisipan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('santri_id', sa.Integer(), nullable=False),
    sa.Column('kategori', sa.String(length=100), nullable=False),
    sa.Column('tanggal_ditetapkan', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['santri_id'], ['santri.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('santri_id')
    )
    op.create_table('pendaftaran',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('santri_id', sa.Integer(), nullable=False),
    sa.Column('rombongan_id', sa.Integer(), nullable=False),
    sa.Column('titik_turun', sa.String(length=100), nullable=False),
    sa.Column('jenis_perjalanan', sa.String(length=20), nullable=True),
    sa.Column('nomor_bus', sa.String(length=20), nullable=True),
    sa.Column('status_pembayaran', sa.String(length=20), nullable=True),
    sa.Column('metode_pembayaran', sa.String(length=20), nullable=True),
    sa.Column('total_biaya', sa.Integer(), nullable=False),
    sa.Column('tanggal_pendaftaran', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['rombongan_id'], ['rombongan.id'], ),
    sa.ForeignKeyConstraint(['santri_id'], ['santri.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('santri_id')
    )
    op.create_table('tarif',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titik_turun', sa.String(length=100), nullable=False),
    sa.Column('harga_bus', sa.Integer(), nullable=False),
    sa.Column('fee_korda', sa.Integer(), nullable=True),
    sa.Column('rombongan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rombongan_id'], ['rombongan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tarif')
    op.drop_table('pendaftaran')
    op.drop_table('partisipan')
    op.drop_table('izin')
    op.drop_table('santri')
    op.drop_table('rombongan')
    # ### end Alembic commands ###
