"""Buat tabel Santri dan tambahkan relasi ke Rombongan

Revision ID: 5171efd9a02b
Revises: 5d11570adbf9
Create Date: 2025-08-04 02:53:52.512286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5171efd9a02b'
down_revision = '5d11570adbf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('santri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_student_id', sa.String(length=50), nullable=False),
    sa.Column('nis', sa.String(length=30), nullable=False),
    sa.Column('nama', sa.String(length=150), nullable=False),
    sa.Column('kabupaten', sa.String(length=100), nullable=True),
    sa.Column('asrama', sa.String(length=50), nullable=True),
    sa.Column('no_hp_wali', sa.String(length=20), nullable=True),
    sa.Column('jenis_kelamin', sa.String(length=10), nullable=True),
    sa.Column('status_rombongan', sa.String(length=30), nullable=True),
    sa.Column('status_pembayaran', sa.String(length=20), nullable=True),
    sa.Column('rombongan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rombongan_id'], ['rombongan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_student_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('santri')
    # ### end Alembic commands ###
