"""Refactor bendahara feature with detailed transactions

Revision ID: 55db64609013
Revises: 759b6bb3199e
Create Date: 2025-08-19 16:12:24.915539

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '55db64609013'
down_revision = '759b6bb3199e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rombongan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_setoran_bus_pulang', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_setoran_bus_kembali', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_setoran_pondok', sa.Integer(), nullable=True))
        batch_op.drop_column('status_setoran_bus')
        batch_op.drop_column('tanggal_setoran_lain')
        batch_op.drop_column('status_setoran_lain')
        batch_op.drop_column('tanggal_setoran_bus')

    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rombongan_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'rombongan', ['rombongan_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('rombongan_id')

    with op.batch_alter_table('rombongan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tanggal_setoran_bus', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('status_setoran_lain', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('tanggal_setoran_lain', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('status_setoran_bus', mysql.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('total_setoran_pondok')
        batch_op.drop_column('total_setoran_bus_kembali')
        batch_op.drop_column('total_setoran_bus_pulang')

    # ### end Alembic commands ###
