"""Tambah metode_pembayaran ke Pendaftaran

Revision ID: 578f1db0fefc
Revises: eb824b5c6f2c
Create Date: 2025-08-04 15:37:05.989186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '578f1db0fefc'
down_revision = 'eb824b5c6f2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pendaftaran', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metode_pembayaran', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pendaftaran', schema=None) as batch_op:
        batch_op.drop_column('metode_pembayaran')

    # ### end Alembic commands ###
