"""Tambah kolom cakupan_wilayah ke Rombongan

Revision ID: 5d11570adbf9
Revises: 
Create Date: 2025-08-04 00:40:34.035067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d11570adbf9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rombongan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cakupan_wilayah', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rombongan', schema=None) as batch_op:
        batch_op.drop_column('cakupan_wilayah')

    # ### end Alembic commands ###
