"""Menambahkan keterangan manual

Revision ID: 666d93108132
Revises: 6fbc08cbd534
Create Date: 2025-09-14 14:22:27.421825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '666d93108132'
down_revision = '6fbc08cbd534'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('santri', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keterangan_manual', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('santri', schema=None) as batch_op:
        batch_op.drop_column('keterangan_manual')

    # ### end Alembic commands ###
