"""merubah api studend unique jadi false

Revision ID: 6f11a78088a1
Revises: 20c453caeaa9
Create Date: 2025-08-31 22:42:43.740487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f11a78088a1'
down_revision = '20c453caeaa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('santri', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('api_student_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('santri', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('api_student_id'), ['api_student_id'], unique=True)

    # ### end Alembic commands ###
