"""add url wali

Revision ID: 6fbc08cbd534
Revises: 6f11a78088a1
Create Date: 2025-09-08 17:01:23.115168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fbc08cbd534'
down_revision = '6f11a78088a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rombongan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grup_wali_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rombongan', schema=None) as batch_op:
        batch_op.drop_column('grup_wali_url')

    # ### end Alembic commands ###
