"""empty message

Revision ID: 712dd31eec7b
Revises: c08c448fd397
Create Date: 2025-08-16 03:00:47.180633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '712dd31eec7b'
down_revision = 'c08c448fd397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wisuda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('santri_nis', sa.String(length=30), nullable=False),
    sa.Column('edisi_id', sa.Integer(), nullable=False),
    sa.Column('kategori_wisuda', sa.String(length=150), nullable=False),
    sa.Column('tanggal_penetapan', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['edisi_id'], ['edisi.id'], ),
    sa.ForeignKeyConstraint(['santri_nis'], ['santri.nis'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('santri_nis')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wisuda')
    # ### end Alembic commands ###
