"""Izinkan rombongan_id di tabel santri untuk null

Revision ID: 74bd45aff9c4
Revises: 5171efd9a02b
Create Date: 2025-08-04 03:22:46.248726

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '74bd45aff9c4'
down_revision = '5171efd9a02b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('santri', schema=None) as batch_op:
        batch_op.alter_column('rombongan_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('santri', schema=None) as batch_op:
        batch_op.alter_column('rombongan_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
