"""Add Bendahara feature models and fields

Revision ID: 759b6bb3199e
Revises: 712dd31eec7b
Create Date: 2025-08-19 01:45:56.203607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '759b6bb3199e'
down_revision = '712dd31eec7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaksi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edisi_id', sa.Integer(), nullable=False),
    sa.Column('deskripsi', sa.String(length=255), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.Column('tipe', sa.String(length=20), nullable=False),
    sa.Column('rekening', sa.String(length=50), nullable=True),
    sa.Column('tanggal', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['edisi_id'], ['edisi.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rombongan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_setoran_bus', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('tanggal_setoran_bus', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status_setoran_lain', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('tanggal_setoran_lain', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rombongan', schema=None) as batch_op:
        batch_op.drop_column('tanggal_setoran_lain')
        batch_op.drop_column('status_setoran_lain')
        batch_op.drop_column('tanggal_setoran_bus')
        batch_op.drop_column('status_setoran_bus')

    op.drop_table('transaksi')
    # ### end Alembic commands ###
