"""Tambah batas_pembayaran dan kuota ke Rombongan

Revision ID: 8575bf6be509
Revises: 4f8339332785
Create Date: 2025-08-05 03:10:49.860172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8575bf6be509'
down_revision = '4f8339332785'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rombongan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batas_pembayaran', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('kuota', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rombongan', schema=None) as batch_op:
        batch_op.drop_column('kuota')
        batch_op.drop_column('batas_pembayaran')

    # ### end Alembic commands ###
