"""Tambah edisi_id ke Pendaftaran dan Partisipan

Revision ID: 94da95abe6d2
Revises: cc4ac340976e
Create Date: 2025-08-11 22:30:05.593869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94da95abe6d2'
down_revision = 'cc4ac340976e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pendaftaran', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edisi_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'edisi', ['edisi_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pendaftaran', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('edisi_id')

    # ### end Alembic commands ###
