"""Add manajemen barang

Revision ID: beb1d03093ee
Revises: 6c713af93d81
Create Date: 2025-08-28 17:58:57.081589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beb1d03093ee'
down_revision = '6c713af93d81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barang_santri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pendaftaran_id', sa.Integer(), nullable=False),
    sa.Column('jumlah_koli', sa.Integer(), nullable=True),
    sa.Column('foto_barang', sa.String(length=255), nullable=True),
    sa.Column('status_absensi', sa.String(length=30), nullable=True),
    sa.Column('dicatat_oleh_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dicatat_oleh_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['pendaftaran_id'], ['pendaftaran.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('izin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_izin_santri_edisi'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('izin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_izin_santri_edisi'), ['santri_id', 'edisi_id'], unique=False)

    op.drop_table('barang_santri')
    # ### end Alembic commands ###
