"""Tambah kolom gelombang_pulang ke Pendaftaran

Revision ID: c7269a8975c3
Revises: 666d93108132
Create Date: 2025-09-15 13:53:11.253413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7269a8975c3'
down_revision = '666d93108132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pendaftaran', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gelombang_pulang', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pendaftaran', schema=None) as batch_op:
        batch_op.drop_column('gelombang_pulang')

    # ### end Alembic commands ###
