"""Tambah fitur countdown ke model Edisi

Revision ID: caf48df08622
Revises: ff4229d07b08
Create Date: 2025-08-10 15:42:17.661615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caf48df08622'
down_revision = 'ff4229d07b08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edisi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('countdown_title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('countdown_target_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edisi', schema=None) as batch_op:
        batch_op.drop_column('countdown_target_date')
        batch_op.drop_column('countdown_title')

    # ### end Alembic commands ###
