"""Tambah URL Google Maps ke model Bus

Revision ID: cc4ac340976e
Revises: caf48df08622
Create Date: 2025-08-11 01:45:14.679544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc4ac340976e'
down_revision = 'caf48df08622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gmaps_share_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bus', schema=None) as batch_op:
        batch_op.drop_column('gmaps_share_url')

    # ### end Alembic commands ###
