"""Tambah sistem Korlapda dan model Absen

Revision ID: cdb6500b01f0
Revises: f4ae60f472fb
Create Date: 2025-08-09 02:15:16.465876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdb6500b01f0'
down_revision = 'f4ae60f472fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('absen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pendaftaran_id', sa.Integer(), nullable=False),
    sa.Column('nama_absen', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('dicatat_oleh_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dicatat_oleh_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['pendaftaran_id'], ['pendaftaran.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bus_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'bus', ['bus_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('bus_id')

    op.drop_table('absen')
    # ### end Alembic commands ###
