"""Re-implementasi relasi pendaftaran lintas rombongan

Revision ID: e32ae384d3fe
Revises: fa6a8690a666
Create Date: 2025-08-08 02:38:00.200637

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e32ae384d3fe'
down_revision = 'fa6a8690a666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pendaftaran', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rombongan_pulang_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rombongan_kembali_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('pendaftaran_ibfk_6'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'rombongan', ['rombongan_pulang_id'], ['id'])
        batch_op.create_foreign_key(None, 'rombongan', ['rombongan_kembali_id'], ['id'])
        batch_op.drop_column('rombongan_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pendaftaran', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rombongan_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('pendaftaran_ibfk_6'), 'rombongan', ['rombongan_id'], ['id'])
        batch_op.drop_column('rombongan_kembali_id')
        batch_op.drop_column('rombongan_pulang_id')

    # ### end Alembic commands ###
