"""Implementasi tabel Pendaftaran dan update model Santri

Revision ID: eb824b5c6f2c
Revises: 74bd45aff9c4
Create Date: 2025-08-04 14:35:02.517601

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb824b5c6f2c'
down_revision = '74bd45aff9c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pendaftaran',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('santri_id', sa.Integer(), nullable=False),
    sa.Column('rombongan_id', sa.Integer(), nullable=False),
    sa.Column('titik_turun', sa.String(length=100), nullable=False),
    sa.Column('jenis_perjalanan', sa.String(length=20), nullable=True),
    sa.Column('nomor_bus', sa.String(length=20), nullable=True),
    sa.Column('status_pembayaran', sa.String(length=20), nullable=True),
    sa.Column('total_biaya', sa.Integer(), nullable=False),
    sa.Column('tanggal_pendaftaran', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['rombongan_id'], ['rombongan.id'], ),
    sa.ForeignKeyConstraint(['santri_id'], ['santri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('santri', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_santri', sa.String(length=20), nullable=True))
        batch_op.drop_constraint(batch_op.f('santri_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('status_pembayaran')
        batch_op.drop_column('rombongan_id')
        batch_op.drop_column('status_rombongan')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('santri', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_rombongan', mysql.VARCHAR(length=30), nullable=True))
        batch_op.add_column(sa.Column('rombongan_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('status_pembayaran', mysql.VARCHAR(length=20), nullable=True))
        batch_op.create_foreign_key(batch_op.f('santri_ibfk_1'), 'rombongan', ['rombongan_id'], ['id'])
        batch_op.drop_column('status_santri')

    op.drop_table('pendaftaran')
    # ### end Alembic commands ###
