"""Tambah kolom titik_jemput_kembali ke Pendaftaran

Revision ID: f4ae60f472fb
Revises: e32ae384d3fe
Create Date: 2025-08-08 13:42:03.393742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4ae60f472fb'
down_revision = 'e32ae384d3fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pendaftaran', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titik_jemput_kembali', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pendaftaran', schema=None) as batch_op:
        batch_op.drop_column('titik_jemput_kembali')

    # ### end Alembic commands ###
