"""Buat tabel Izin dan update model Santri untuk status

Revision ID: f92fb2587963
Revises: 578f1db0fefc
Create Date: 2025-08-04 16:50:34.792415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f92fb2587963'
down_revision = '578f1db0fefc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('izin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('santri_id', sa.Integer(), nullable=False),
    sa.Column('tanggal_berakhir', sa.Date(), nullable=False),
    sa.Column('keterangan', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['santri_id'], ['santri.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('santri_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('izin')
    # ### end Alembic commands ###
