"""empty message

Revision ID: fa3e71e40e07
Revises: 0d3b7caa114e
Create Date: 2025-08-12 02:01:17.067990

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa3e71e40e07'
down_revision = '0d3b7caa114e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('santri', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama_jabatan', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('status_jabatan', sa.String(length=100), nullable=True))
        batch_op.drop_column('jabatan')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('santri', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jabatan', mysql.JSON(), nullable=True))
        batch_op.drop_column('status_jabatan')
        batch_op.drop_column('nama_jabatan')

    # ### end Alembic commands ###
