"""Sederhanakan relasi Rombongan ke Pendaftaran

Revision ID: fa6a8690a666
Revises: 014339160986
Create Date: 2025-08-08 02:24:15.386655

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa6a8690a666'
down_revision = '014339160986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pendaftaran', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rombongan_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('pendaftaran_ibfk_3'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('pendaftaran_ibfk_4'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'rombongan', ['rombongan_id'], ['id'])
        batch_op.drop_column('rombongan_pulang_id')
        batch_op.drop_column('rombongan_kembali_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pendaftaran', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rombongan_kembali_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rombongan_pulang_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('pendaftaran_ibfk_4'), 'rombongan', ['rombongan_pulang_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('pendaftaran_ibfk_3'), 'rombongan', ['rombongan_kembali_id'], ['id'])
        batch_op.drop_column('rombongan_id')

    # ### end Alembic commands ###
