"""Tambah status ke model Izin

Revision ID: ff4229d07b08
Revises: f0f56e4cf646
Create Date: 2025-08-10 02:40:42.111345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff4229d07b08'
down_revision = 'f0f56e4cf646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('izin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('izin', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
